docker run -p 5432:5432 -d \
    --name sistema-vacinacao \
    -e POSTGRES_PASSWORD=postgres \
    -e POSTGRES_USER=postgres \
    -e POSTGRES_DB=sistema-vacinacao \
    -v pgdata:/var/lib/postgresql/data \
    postgres
